[TEST] DP-15628 toc hotspot
massgov/mayflower pull request #1070
Opened 2020-05-21 19:32 UTC by ygannett

Any PRs being created needs a changelog.txt file before being merged into dev. See: [Change Log Instructions](https://github.com/massgov/mayflower/blob/develop/docs/for-developers/changelog-instructions.md)

## Description

## Related Issue / Ticket

- [JIRA issue]()
- [Github issue]()

## Steps to Test

1.

## Screenshots
Use something like [licecap](http://www.cockos.com/licecap/) to capture gifs to demonstrate behaviors.

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application

*

#### @TODO

*

#### Today I learned...

2020-05-21 20:29 UTC, tom-fleming commented on patternlab/styleguide/source/assets/js/modules/expandClickable.js
> +// export default (function (window, document) { // NEITHER OF THEM WORK WITH THIS.
It looks like you would need to include jQuery to get this to work. You can change this line to something like this `export default (function (window, document, $) {` and then you would need to replace the bottom line with this `})(window, document, jQuery);`

2020-06-08 17:55 UTC, danstafford requested changes
Looks good @ygannett ! The only thing I noticed is that on the binder cover page when I hover over the  nested links they all get an underline regardless of which one you hover over.
http://localhost:3000/patterns/05-pages-binder-page-cover/05-pages-binder-page-cover.html#
<img width="973" alt="05-pages-binder-page-cover" src="https://user-images.githubusercontent.com/11247942/84063860-b4fb3180-a98f-11ea-9a55-60c7575fcb46.png">

2020-06-09 14:25 UTC, ygannett commented
@danstafford Thank you for the thorough review.  It's fixed.  Can you review that?

2020-06-09 20:35 UTC, danstafford approved these changes

2020-06-09 20:36 UTC, merged