DP-17200 Add horizontal nav code into global nav branch so it can be used on home page
massgov/mayflower pull request #1094
Opened 2020-06-18 16:16 UTC by arthurbaghdas

## Description
Main nav version horizontal is exactly the same as it should be to not affect anything.
New templates added for the main nav version hamburger.

Main nav hamburger template
Header with hamburger menu template
Homepage with Hamburger menu template.
Header mixed (With the horizontal nav and hamburger for different screen sizes)
Homepage mixed (Page template with mixed header) 

## Related Issue / Ticket

- [JIRA issue] DP-17200

#### Impacted Areas in Application
Header and main navigation

2020-06-19 14:03 UTC, ygannett requested changes
@arthurbaghdas This looks great.  A little thing I noticed.  Please see my comment below.

Here are a couple more things I noticed:

1. With the desktop display in the Hamburger version (screen width > 840 px), the Google translate is missing from the utility nav bar (dark blue bar on the top).  Please display that one.
<img width="874" alt="ham-google-translate" src="https://user-images.githubusercontent.com/9633303/85142018-bc370080-b215-11ea-9456-25d54174b14f.png">

2. In the dropdown of the hamburger, no Google translate is shown whether it's desktop or mobile displays.

3. I'm not sure this is supposed to resolved here or not, but just bring this up. The visual cues of the items in the dropdown for button vs. link are not consistent.  This needs some design decisions before making any changes.
<img width="772" alt="ham-dropdown" src="https://user-images.githubusercontent.com/9633303/85142255-1041e500-b216-11ea-9133-8b2851d11686.png">

2020-06-19 14:03 UTC, ygannett commented on patternlab/styleguide/source/_patterns/03-organisms/by-template/header-mixed.twig
> +    </div>
@arthurbaghdas It seems LL. 61-66 is not necessary.  That part is the buttons in mobile in the original header. Since we have the hamburger one in mobile with this mixed version, I don't think we need them.  Can you confirm?

2020-06-19 14:04 UTC, arthurbaghdas commented on patternlab/styleguide/source/_patterns/03-organisms/by-template/header-mixed.twig
> +    </div>
I think I will agree with you.

2020-06-22 11:18 UTC, arthurbaghdas commented
Hey @ygannett .
Google translate issue fixed, The code which is not used was removed. However I'm not sure I should proceed with the changes on point N 3 . I agree this needs a design decision

2020-06-23 13:31 UTC, ygannett commented
@arthurbaghdas  Thank you for taking care of them.  Im sorry that I should have been more specific.  I see the Google translate is fixed with the mixed one: https://mayflower.digital.mass.gov/patternlab/b/patternlab/DP-17200-add-horizontal-nav-code-branch/patterns/05-pages-Homepage-mixed/05-pages-Homepage-mixed.html
but not in the hamburger one:  https://mayflower.digital.mass.gov/patternlab/b/patternlab/DP-17200-add-horizontal-nav-code-branch/patterns/05-pages-Homepage-hamburger/05-pages-Homepage-hamburger.html

Also, the branch has merge conflicts.  This should be resolved by updating the backstop reference.

2020-06-23 15:42 UTC, arthurbaghdas commented
@ygannett , ready for review.

2020-06-24 13:12 UTC, ygannett approved these changes
Thank you for the all fixes.

2020-10-19 14:51 UTC, tom-fleming approved these changes

2020-10-19 18:45 UTC, merged