add yalc and scripts at root
massgov/mayflower pull request #1153
Opened 2020-08-18 16:32 UTC by clairesunstudio

Any PRs being created needs a changelog.txt file before being merged into dev. See: [Change Log Instructions](https://github.com/massgov/mayflower/blob/develop/docs/for-developers/changelog-instructions.md)

## Description

## Related Issue / Ticket

- [JIRA issue]()
- [Github issue]()

## Steps to Test

1.

## Screenshots
Use something like [licecap](http://www.cockos.com/licecap/) to capture gifs to demonstrate behaviors.

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application

*

#### @TODO

*

#### Today I learned...

2020-08-18 21:41 UTC, smurrayatwork requested changes
Yalc is meant to be a tool for testing or developing WIP packages locally and should not be used as a replacement for the concept of workspaces or other techniques. I'm also not so sure that symlinks work so well with CircleCI in the manner that this PR is currently implemented.

2020-08-19 15:38 UTC, clairesunstudio commented on .circleci/config.yml
> +          root: ~/repo
```suggestion
          root: ~/repo/patternlab
```

2020-08-19 15:38 UTC, clairesunstudio commented on .circleci/config.yml
>            root: ~/repo
```suggestion
          root: ~/repo/react
```

2020-08-19 15:40 UTC, clairesunstudio commented on .circleci/config.yml
>            root: ~/repo
```suggestion
          root: ~/repo/site
```

2020-08-19 15:40 UTC, clairesunstudio commented on .circleci/config.yml
> +          paths: ["site"]
```suggestion
          paths: ["*"]
```

2020-08-19 15:40 UTC, clairesunstudio commented on .circleci/config.yml
> +          paths: ["react"]
```suggestion
          paths: ["*"]
```

2020-08-19 15:40 UTC, clairesunstudio commented on .circleci/config.yml
> +          paths: ["patternlab"]
```suggestion
          paths: ["*"]
```

2020-08-19 16:29 UTC, clairesunstudio commented on .circleci/config.yml
>      <<: *patternlab_defaults
```suggestion
```

2020-10-14 17:54 UTC, closed without merging