React/update footer info
massgov/mayflower pull request #164
Opened 2018-08-15 19:21 UTC by clairesunstudio

https://jira.mass.gov/browse/DP-10069

fix currently hard-coded year in search footer:
before:
![screen shot 2018-08-15 at 3 24 19 pm](https://user-images.githubusercontent.com/5789411/44168508-7f40d680-a09f-11e8-90b5-bc9c57fa7998.png)

after:
![screen shot 2018-08-15 at 3 24 34 pm](https://user-images.githubusercontent.com/5789411/44168518-8bc52f00-a09f-11e8-8b99-e870d273ddcf.png)

2018-08-17 18:08 UTC, avrilpearl requested changes
Based on discussions - i think we should make all of these strings passable props to the footer component, and make the mass.gov setting hardcoded here the default values. - let me know when you want me to look at those changes!

2018-08-20 12:47 UTC, pmallett-mc requested changes
minor fix needed in propTypes

2018-08-20 12:47 UTC, pmallett-mc commented on react/src/components/organisms/Footer/index.js
> +  footeLogo: PropTypes.shape({
typo in footer for this propType member

2018-08-20 18:31 UTC, pmallett-mc approved these changes

2018-08-20 21:03 UTC, avrilpearl approved these changes

2018-08-20 21:36 UTC, merged