Patternlab/header mixed keyboard a11y
massgov/mayflower pull request #1759
Opened 2023-04-05 21:54 UTC by clairesunstudio

2023-04-10 18:55 UTC, clairesunstudio commented on packages/patternlab/styleguide/source/assets/js/modules/mainNav.js
> +          $dropdownLinks[dropdownIndex].focus();
```suggestion
          $dropdownLinks[dropdownIndex].focus(); 

```
Unsure why this is not working. See the first up/down arrow keypress on the top level
![main-nav-keyboard](https://user-images.githubusercontent.com/5789411/230972972-6388f1c8-c44e-473a-b4e2-935e5aed364d.gif)

2023-04-18 21:12 UTC, ygannett requested changes
The key commands are working beautifully, but when trying to access the sub menu drop-downs with mouse, the drop-downs don't stay open as leaving the top menu area.  So, unable to click submenus.

2023-04-20 17:52 UTC, clairesunstudio commented
Good catch! Fixed!

https://mayflower.digital.mass.gov/patternlab/b/patternlab/header-mixed-keyboard-a11y/patterns/03-organisms-by-template-header-mixed/03-organisms-by-template-header-mixed.html

2023-04-24 14:10 UTC, ygannett approved these changes
LGTM.

2023-04-24 14:37 UTC, ygannett commented
@clairesunstudio After I approved the PR, noticed this backstop failure:  https://output.circle-artifacts.com/output/job/2618e62c-b8f2-408e-8ff4-e64649f58f3e/artifacts/0/backstop/reports/html/index.html
Since this sample page is not relevant to us anymore, would you like to remove it?

2023-04-24 18:59 UTC, merged