DP-10057: Mayflower React: Port Tooltip Molecule in Mayflower React
massgov/mayflower pull request #198
Opened 2018-08-28 22:58 UTC by mark-casias

## Description
Port this molecule from PL https://mayflower.digital.mass.gov/?p=molecules-tooltip into mayflower react.

## Screenshots
user-images.githubusercontent.com/7987464/44755470-83c7af00-aae3-11e8-8f2c-ed8cf76a94f9.png)

2018-09-14 16:12 UTC, clairesunstudio requested changes

2018-09-14 16:12 UTC, clairesunstudio commented on react/src/components/atoms/icons/SvgQuestionMark/index.js
> +import React from 'react';
can you please update the icon in tooltip to use the new Icon component that just got merged in?

2018-09-14 19:22 UTC, mark-casias commented on react/src/components/atoms/icons/SvgQuestionMark/index.js
> +import React from 'react';
Added latest development, removed solo Questionmark svg component, added questionmark svg to icon listings. Replaced quesitonmark component call to use Icon. Updated backstop. Updated changelog.

2018-09-24 16:36 UTC, mark-casias commented
@clairesunstudio can we get this reviewed and passed please?

2018-09-25 12:43 UTC, pmallett-mc approved these changes

2018-09-27 18:51 UTC, clairesunstudio requested changes

2018-09-27 18:51 UTC, clairesunstudio commented on react/src/components/molecules/Tooltip/style.scss
> +.ma__tooltip {
are these styles direct copy from assets/scss? if so, can you use @import instead

2018-09-27 18:57 UTC, clairesunstudio commented on react/src/components/molecules/Tooltip/Tooltip.stories.js
> +      openText: 'Want more information?',
can you also add knobs to the story?

2018-09-27 21:07 UTC, clairesunstudio commented
Tooltip component bug in Patternlab and React: 
![tooltip-bug](https://user-images.githubusercontent.com/5789411/46174693-b6e29700-c277-11e8-9753-5452d6c48bcd.gif)
We should follow up on this in a different pr

2018-09-27 21:08 UTC, clairesunstudio approved these changes

2018-09-27 21:08 UTC, merged