React/dp 10134  refactor backstop scenarios
massgov/mayflower pull request #201
Opened 2018-08-29 15:36 UTC by pmallett-mc

## Description
Updates the mf/react Backstop implementation to discover all stories by parsing each story module to find the `kind` and `storyName` values instead of assuming they will match the path and module dir name.

Additional changes/improvements:
* added better documentation in /mayflower/react/docs/visual-regression.md
* added backstop:approve npm run command to facilitate update workflow (doc updated to use npm run commands mostly instead of docker-compose directly)
* incorporated Steven's suggestion to use path.resolve for backstop paths
* added support for a --debug flag to help with local debugging

## Related Issue / Ticket
- [JIRA issue https://jira.mass.gov/browse/DP-10134](https://jira.mass.gov/browse/DP-10134)

## Steps to Test
Tests in CI should pass for this branch -- other pending PRs will need to update their reference images after this is merged.

If you would like to test locally:
1. cd react
1. git checkout react/DP-10134--refactor-backstop-scenarios
1. npm install
1. npm run backstop # all tests should pass, run takes ~3min
1. edit a component to test for a failure. eg. remove the className prop in Button
1. npm run backstop # the Button atom test should fail
1. open backstop/data/html_report/index.html

## Screenshots
N/A

## Additional Notes:
N/A

#### Impacted Areas in Application

* react backstop tests

#### @TODO

*

#### Today I learned...

2018-08-29 17:26 UTC, pmallett-mc commented
@smurrayatwork pointed out that we may be able to discover kind & storyNames using the Storybook API: https://storybook.js.org/addons/api/
But I am not seeing any way to get that into the node script to create the scenarios.
I found this issue asking for a way to do it with no resolution other than to "do what Storyshots does"
https://github.com/storybooks/storybook/issues/1208

Unless Im missing something, it looks like Storyshots does the naive thing I was doing before: assume the filename is the only test story name: https://github.com/storybooks/storybook/blob/master/addons/storyshots/storyshots-core/src/Stories2SnapsConverter.js

2018-08-29 19:17 UTC, smurrayatwork approved these changes

2018-08-31 15:31 UTC, mark-casias approved these changes
tested locally and passed.

2018-08-31 18:54 UTC, clairesunstudio commented
I don't see atoms like buttons, forms, headings in the screenshots --> https://3854-137521197-gh.circle-artifacts.com/0/backstop/data/html_report/index.html

2018-09-04 15:04 UTC, smurrayatwork commented
Changes:
- You no longer need the backstop atoms command; this will now process all components with component level viewport overrides as needed.
- All references have been updated so that all components are pulled into the backstop command without `--atoms`.

2018-09-04 16:56 UTC, mrjmd requested changes
A couple of small considerations noted in comments, I think updating the docs is the only approval blocker.

2018-09-04 16:56 UTC, mrjmd commented on react/backstop/backstop.js
> +];
Should this be an exported const so we're not duplicating these values between ``backstop.js`` and ``storyBookBackstop.js`` ?

2018-09-04 16:56 UTC, mrjmd commented on react/backstop/storyBookBackstop.js
> +    && (filePath.indexOf('icons') === -1);
These exceptions could probably use comments explaining why they are needed, as they had in the previous version.

2018-09-04 16:56 UTC, mrjmd commented on react/backstop/storyBookBackstop.js
> +
Double white space.

2018-09-04 16:56 UTC, mrjmd commented on react/docs/visual-regression.md
> +npm run backstop:atoms
Does this need to be updated?

2018-09-04 18:14 UTC, mrjmd approved these changes
Changes look good!

2018-09-04 19:51 UTC, avrilpearl approved these changes
worked as described!

2018-09-04 19:51 UTC, merged

2018-09-10 13:26 UTC, pmallett-mc commented on react/backstop/backstop.js
> +];
Yea, I think that would be a good change; move into storyBookBackstop & ref from there instead.