React/filter box refactor
massgov/mayflower pull request #277
Opened 2018-09-27 19:49 UTC by clairesunstudio

2018-09-27 21:45 UTC, pmallett-mc requested changes
This looks pretty good, but the FilterBox is failing to render in Storybook when I test this in conjunction w/ the latest develop:
![filterbox-errors](https://user-images.githubusercontent.com/38226003/46176276-1b97f480-c26c-11e8-8535-98ecfceaa3bb.png)

Also, though SearchBanner functions, there are a lot of console warnings, mostly "Warning: Encountered two children with the same key"

I also think this should be tested out with Search & we should have a PR to go in with it, after all, if nothing can use this, there's no reason to rush into it.

2018-09-27 21:45 UTC, pmallett-mc commented on react/src/components/organisms/FilterBox/index.js
> +                <div className={field.class}>
these will need a `key` attribute now

2018-09-28 03:09 UTC, clairesunstudio commented
@petermallett good catch! updated and fixed filterbox. This is part of the search banner work I'm doing for mobile responsiveness for EEC. I separated this out so that it's easier to review. I created a pr in search just so we don't forget, but it won't work until https://github.com/massgov/massgov-search/pull/326 and https://github.com/massgov/massgov-search/pull/327 get in so that we can bring in the new mayflower. We should spend some time next week to get those resolved

2018-09-28 03:10 UTC, clairesunstudio commented
But for now, please review this so that i can continue working on search banner styles for EEC. thanks!

2018-09-28 15:44 UTC, clairesunstudio commented on react/src/components/utilities/componentPropTypeCheck.js
> +      if (typeof child.component.type === 'string') {
do you mean `child.component.type.name` here?

2018-09-28 15:45 UTC, clairesunstudio commented on react/src/components/utilities/componentPropTypeCheck.js
> +      return child.component.type.name &&
this seems repetitive to the one above

2018-09-28 15:45 UTC, clairesunstudio commented on react/src/components/utilities/componentPropTypeCheck.js
> +    return new Error(`Invalid prop ${propName} supplied to ${componentName}. Got: ${component || 'undefined'}. Validation failed.`);
the error message doesn't return the component name correctly

2018-09-28 15:51 UTC, clairesunstudio commented
error message example:
![screen shot 2018-09-28 at 11 19 55 am](https://user-images.githubusercontent.com/5789411/46219218-be0bb280-c314-11e8-8dc0-0d8ffed7a619.png)

2018-09-28 18:31 UTC, merged