Add react tables
massgov/mayflower pull request #289
Opened 2018-10-03 21:47 UTC by clairesunstudio

2018-10-04 17:30 UTC, smurrayatwork commented on react/src/components/datavis/DataTable/index.js
> +import '../../../../node_modules/react-table/react-table.css';
This shouldn't use a relative path. You should be able to do 'react-table/react-table.css';

2018-10-10 14:57 UTC, avrilpearl commented on react/src/components/datavis/DataTable/county.data.json
> +[
can we rename this to knobs options to match the other components

2018-10-10 14:58 UTC, avrilpearl commented on react/src/components/datavis/DataTable/styles.scss
> +}
can you rename the town.data.json to knobs options to match other components.

2018-10-10 15:05 UTC, avrilpearl requested changes

2018-10-10 15:05 UTC, avrilpearl commented on react/src/components/datavis/DataTable/DataTable.md
> +### Description
can we rename this folder in the components from `datavis` to `dataviz` to match storybook syntax.

2018-10-10 15:06 UTC, avrilpearl commented on react/src/components/datavis/DataTable/styles.scss
> +.ReactTable {
can we reduce the font-size in the table?

2018-10-10 20:05 UTC, avrilpearl approved these changes
looks good! just respond to steven's comment

2018-10-11 19:26 UTC, smurrayatwork approved these changes

2018-10-12 13:28 UTC, merged