add social media icons into Icon options
massgov/mayflower pull request #712
Opened 2019-08-19 20:38 UTC by clairesunstudio

2019-08-20 20:20 UTC, ygannett requested changes
@clairesunstudio Please see the following comments.

2019-08-20 20:20 UTC, ygannett commented on react/src/components/molecules/SocialLinks/index.js
>        title={socialLink.altText}
Please remove `title` which is replaced with `aria-label`.

2019-08-20 20:20 UTC, ygannett commented on react/src/components/atoms/icons/Icon/index.js
> +    fill: PropTypes.string
Any reason to use `fill` directly instead of via css?

2019-08-21 16:21 UTC, clairesunstudio commented on react/src/components/molecules/SocialLinks/index.js
>        title={socialLink.altText}
`title` shows more information to the non-SR users, e.g. when mouse over the icon, it explains what the icon is, which is not completely replaceable by aria-label. I wonder here if there's any harm to SR users to have both

2019-08-21 16:24 UTC, clairesunstudio commented on react/src/components/atoms/icons/Icon/index.js
> +    fill: PropTypes.string
So `fill` is fully ecapsulate into the svg while css classes change the style from outside. If an svg has a fill attribute already, it css doesn't work. This is will make icon styling more componentized.

2019-08-22 13:32 UTC, ygannett commented on react/src/components/molecules/SocialLinks/index.js
>        title={socialLink.altText}
If they are in a condition to be able to see the title value, users would benefit from that.
Here is what I mentioned as the inconsistent implementation of `title`...
The [W3C HTML5 Recommendation](https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute) warns against use of the title attribute:

> Relying on the title attribute is currently discouraged as many user agents do not expose the attribute in an accessible manner as required by this specification (e.g., requiring a pointing device such as a mouse to cause a tooltip to appear, which excludes keyboard-only users and touch-only users, such as anyone with a modern phone or tablet).

When both, `title` and `aria-label` are added, screen reader could read both values depending on combinations of OS and devices.  Screen reader users would listen the same content twice, which is not so good user experience.

2019-08-22 13:44 UTC, ygannett commented on react/src/components/atoms/icons/Icon/index.js
> +    fill: PropTypes.string
Right.  By adding `fill` directly in `svg` here, you don't want the icons to set different colors from outside (= css) even they are used somewhere else?

2019-08-23 19:13 UTC, clairesunstudio commented on react/src/components/molecules/SocialLinks/index.js
>        title={socialLink.altText}
I see. Are you good with removing `title`? The only thing would be there will not be a tooltip to explain the icons

2019-08-23 19:13 UTC, clairesunstudio commented on react/src/components/atoms/icons/Icon/index.js
> +    fill: PropTypes.string
it should be able to override --> https://codepen.io/team/css-tricks/pen/yebOYp

2019-08-23 19:31 UTC, ygannett commented on react/src/components/molecules/SocialLinks/index.js
>        title={socialLink.altText}
It doesn't seem any reasonable alternative is available right now, but we'll continue research for non-screen reader users.

2019-08-23 19:34 UTC, ygannett commented on react/src/components/atoms/icons/Icon/index.js
> +    fill: PropTypes.string
Ok, let's go with this change.

2019-08-23 19:34 UTC, ygannett approved these changes

2019-08-23 19:35 UTC, merged