add circle auto changelog
massgov/mayflower pull request #722
Opened 2019-08-26 21:41 UTC by clairesunstudio

As we are going to automate our release process. Auto consolidate changelogs depends on all prs have a changelog that follows certain standards. This pr adds a circle task to automate adding changelog to dependabot prs
<img width="743" alt="Screen Shot 2019-08-27 at 5 48 52 PM" src="https://user-images.githubusercontent.com/5789411/63810553-f9cb4580-c8f2-11e9-8e26-c23058ace480.png">

2019-08-29 14:54 UTC, avrilpearl commented
(1) Can we label these [Dependency]
(2) Can you separate Security ones in type: Security and straight-up non-security related fixes in type: Changed.

2019-08-29 14:54 UTC, avrilpearl requested changes
see comment above re:type and component label

2019-08-29 18:37 UTC, mrossi113 reviewed
I just have a few comments.

2019-08-29 18:37 UTC, mrossi113 commented on .circleci/config.yml
> +            chmod +x ./.circleci/dependabot.sh
@clairesunstudio you can `chmod +x ./.circleci/dependabot.sh` and then commit to the PR instead.

2019-08-29 18:37 UTC, mrossi113 commented on .circleci/config.yml
> +            - "a7:d5:55:42:fe:37:52:b6:71:7c:a6:d8:05:78:fd:25"
This could be an environment variable in CircleCI instead adding directly in  the config.yml file.

2019-08-29 18:37 UTC, mrossi113 commented on .circleci/dependabot.sh
> +  echo "- [Dependencies] $lastCommit" >> changelogs/dependabot.md
Is all dependbot PRs using only one changelog?

2019-08-30 00:47 UTC, clairesunstudio commented on .circleci/config.yml
> +            - "a7:d5:55:42:fe:37:52:b6:71:7c:a6:d8:05:78:fd:25"
good call will add that to circle

2019-08-30 00:48 UTC, clairesunstudio commented on .circleci/config.yml
> +            chmod +x ./.circleci/dependabot.sh
the push to pr part is in the shell script

2019-08-30 00:49 UTC, clairesunstudio commented on .circleci/dependabot.sh
> +  echo "- [Dependencies] $lastCommit" >> changelogs/dependabot.md
yes, they will all be in one file. do you want them to be separate? based on our conversation last week I thought there would be no difference on your end.

2019-08-30 14:17 UTC, mrossi113 commented on .circleci/dependabot.sh
> +  echo "- [Dependencies] $lastCommit" >> changelogs/dependabot.md
No, that is fine I was just trying to understand this PR.

2019-08-30 14:18 UTC, mrossi113 commented on .circleci/config.yml
> +            chmod +x ./.circleci/dependabot.sh
Right, but you want to make the shell script executable correct?

2019-09-03 13:25 UTC, clairesunstudio commented on .circleci/config.yml
> +            chmod +x ./.circleci/dependabot.sh
yep, this is the line to make it executable

2019-09-11 15:12 UTC, avrilpearl approved these changes

2019-09-11 15:13 UTC, mrossi113 approved these changes
👍 LGTM!

2019-09-11 15:37 UTC, merged