DP-15349 MF Add text fade to service page overview for flexible link groups
massgov/mayflower pull request #735
Opened 2019-09-10 13:28 UTC by lannyheidbreder-mc

## Description
Added collapsible/expandable text fade to overview paragraphs on ServiceFlexibleLinkGroups page component.

## Related Issue / Ticket

- [JIRA issue](https://jira.mass.gov/browse/DP-15349)

## Steps to Test

#### Go here and do this

In Mayflower, go to `?p=pages-service-flexible-link-groups` in a sufficiently narrow browser window. (970px or smaller should suffice.)

#### What you should see

The intro text is truncated and fades out toward the bottom, and a button matching the design spec allows you to expand and collapse the area.

At browser widths above 840px (yet small enough to trigger the truncation at all), six lines of text (or equivalent height) should be fully or partially visible.

At 840px or below, four lines of text (or equivalent height) should be fully or partially visible.

## Screenshots

![Screen Shot 2019-09-10 at 8 22 07 AM](https://user-images.githubusercontent.com/52927667/64617501-33488a00-d3a4-11e9-9234-8629538ea9bc.png)
![Screen Shot 2019-09-10 at 8 22 26 AM](https://user-images.githubusercontent.com/52927667/64617503-33488a00-d3a4-11e9-8880-4c965ad5e0b8.png)

## Additional Notes:

I think we will need to add some classes to `activateBodyTextTruncation.js` to affect mass.gov properly; the classes I'm targeting are Mayflower-only, I suspect. I don't think it will require actual back-end work, though I could be wrong about that.

When this hits develop, [DP-8847](https://jira.mass.gov/browse/DP-8847) "should" be quick and easy to finish.

See my assessment of the design spec in the comment on the JIRA ticket.

#### Impacted Areas in Application

A single Mayflower component, for now.

2019-09-25 20:13 UTC, ygannett requested changes
This is working great!

I have a couple of things to mention for accessibility and design.

**Accessibility**:  The "Show more/less" button doesn't give any context to screen reader users. They wouldn't know WHAT to show more/less as they reach the button.  Let's add **aria-label** to `<button>` to tell what to show/hide.  Using the words "show" and "hide" for screen reader users since they don't see the visual presentation and they reach the button before the associated content.  Its value should reflects its state.
       - Visible label = "Show more" --> aria-label="Show the overview."
       - Visible label = "Show less" --> aria-label="Hide the overview."

**Design** :  The alignment of the button doesn't follow our existing design pattern. The design team pointed to this pattern:  https://mayflower.digital.mass.gov/?p=organisms-sticky-toc
<img width="675" alt="Pattern_Lab_-_organisms-sticky-toc" src="https://user-images.githubusercontent.com/9633303/65635529-80387d00-dfae-11e9-81a2-8572f37ac91d.png">
Let's set left align the button.

2019-09-25 21:56 UTC, lannyheidbreder-mc commented
@ygannett, the button alignment is as requested in this ticket’s original mockup; any changes would be considered a scope change and would require review by a designer or manager and so would require a new ticket. Also, per Joe's request that accessibility updates to patterns be tracked appropriately, please create a new ticket for those changes.

2019-09-26 12:57 UTC, joeg8612 commented
@lannyheidbreder-mc I think that the accessibility change requested is directly related to the code written so is in scope for this PR.   I am fine with any design changes being ticketed as a potential change for later.  The design team spec'ed out this design and reviewed the implementation on my laptop.   cc @ygannett

2019-09-27 15:42 UTC, ygannett approved these changes
It looks great.  Thank you for all work.

2019-10-08 18:37 UTC, avrilpearl reviewed
still working on review js locally

2019-10-08 18:37 UTC, avrilpearl commented on assets/scss/00-base/mixins/_ma-truncated-body-text.scss
> +      rgba(#fff, 0) 0%,
```suggestion
      rgba($c-white 0) 0%,
```

2019-10-08 18:37 UTC, avrilpearl commented on assets/scss/00-base/mixins/_ma-truncated-body-text.scss
> +      rgba(#fff, 1) 100%
```suggestion
      rgba($c-white, 1) 100%
```

2019-10-08 18:37 UTC, avrilpearl commented on assets/scss/00-base/mixins/_ma-truncated-body-text.scss
> +    color: $c-bay-blue;
```suggestion
    color: $c-primary;
```

2019-10-08 18:37 UTC, avrilpearl commented on patternlab/styleguide/source/assets/js/helpers/listing.js
> +import activateBodyTextTruncation from "../modules/activateBodyTextTruncation.js";
not sure why this import is here, seems to be removable:
```suggestion
```

2019-10-08 18:37 UTC, avrilpearl commented on assets/scss/00-base/mixins/_ma-truncated-body-text.scss
> +      opacity: 0.5;
i think this should not have an opacity but be $c-primary-lightest;

2019-10-08 19:26 UTC, avrilpearl approved these changes

2019-10-08 19:27 UTC, merged